INSERT INTO product_category (name) VALUES('Art');
INSERT INTO product_category (name) VALUES('Electronics');
INSERT INTO product_category (name) VALUES('Entertainment');
INSERT INTO product_category (name) VALUES('Fashion');
INSERT INTO product_category (name) VALUES('Furniture');
INSERT INTO product_category (name) VALUES('Home & Garden');
INSERT INTO product_category (name) VALUES('Sports');
INSERT INTO product_category (name) VALUES('Vehicles');

INSERT INTO product_condition (condition) VALUES('New');
INSERT INTO product_condition (condition) VALUES('Used - Like New');
INSERT INTO product_condition (condition) VALUES('Used - Very Good');
INSERT INTO product_condition (condition) VALUES('Used - Good');
INSERT INTO product_condition (condition) VALUES('Used - Acceptable');
INSERT INTO product_condition (condition) VALUES('Used - Sold as is');
<<<<<<< HEAD

INSERT INTO product_product (name, price, description, "CreatedAt", "SoldOrNot","categoryID_id", "ConditionID_id")
VALUES ('Smart TV', 20.00, 'An LG smart tv, with remote and power cable', '2021-08-09 13:57:40', 0, 2, 2);
INSERT INTO product_product (name, price, description, "CreatedAt", "SoldOrNot","categoryID_id", "ConditionID_id")
VALUES ('Dr. Martin boots', 10.00, 'Nearly new, no wear and tear. Don´t smell', '2021-09-10 13:45:00', 0, 4, 2);
=======

INSERT INTO product_product (name, price, description, "CreatedAt", "SoldOrNot","categoryID_id", "ConditionID_id")
VALUES ('Smart TV', 20.00, 'An LG smart tv, with remote and power cable', '2021-08-09 13:57:40', 0, 2, 2);
INSERT INTO product_product (name, price, description, "CreatedAt", "SoldOrNot","categoryID_id", "ConditionID_id")
VALUES ('Dr. Martin boots', 10.00, 'Nearly new, no wear and tear. Don´t smell', '2021-09-10 13:45:00', 0, 4, 2);

/*USER INSERTS*/
/*country table*/
INSERT INTO user_country (name) VALUES('Afghanistan');
INSERT INTO user_country (name) VALUES('Albania');
INSERT INTO user_country (name) VALUES('Algeria');
INSERT INTO user_country (name) VALUES('Andorra');
INSERT INTO user_country (name) VALUES('Angola');
INSERT INTO user_country (name) VALUES('Anguilla');
INSERT INTO user_country (name) VALUES('Antigua & Barbuda');
INSERT INTO user_country (name) VALUES('Argentina');
INSERT INTO user_country (name) VALUES('Armenia');
INSERT INTO user_country (name) VALUES('Australia');
INSERT INTO user_country (name) VALUES('Austria');
INSERT INTO user_country (name) VALUES('Azerbaijan');
INSERT INTO user_country (name) VALUES('Bahamas');
INSERT INTO user_country (name) VALUES('Bahrain');
INSERT INTO user_country (name) VALUES('Bangladesh');
INSERT INTO user_country (name) VALUES('Barbados');
INSERT INTO user_country (name) VALUES('Belarus');
INSERT INTO user_country (name) VALUES('Belgium');
INSERT INTO user_country (name) VALUES('Belize');
INSERT INTO user_country (name) VALUES('Benin');
INSERT INTO user_country (name) VALUES('Bermuda');
INSERT INTO user_country (name) VALUES('Bhutan');
INSERT INTO user_country (name) VALUES('Bolivia');
INSERT INTO user_country (name) VALUES('Bosnia & Herzegovina');
INSERT INTO user_country (name) VALUES('Botswana');
INSERT INTO user_country (name) VALUES('Brazil');
INSERT INTO user_country (name) VALUES('Brunei Darussalam');
INSERT INTO user_country (name) VALUES('Bulgaria');
INSERT INTO user_country (name) VALUES('Burkina Faso');
INSERT INTO user_country (name) VALUES('Myanmar/Burma');
INSERT INTO user_country (name) VALUES('Burundi');
INSERT INTO user_country (name) VALUES('Cambodia');
INSERT INTO user_country (name) VALUES('Cameroon');
INSERT INTO user_country (name) VALUES('Canada');
INSERT INTO user_country (name) VALUES('Cape Verde');
INSERT INTO user_country (name) VALUES('Cayman Islands');
INSERT INTO user_country (name) VALUES('Central African Republic');
INSERT INTO user_country (name) VALUES('Chad');
INSERT INTO user_country (name) VALUES('Chile');
INSERT INTO user_country (name) VALUES('China');
INSERT INTO user_country (name) VALUES('Colombia');
INSERT INTO user_country (name) VALUES('Comoros');
INSERT INTO user_country (name) VALUES('Congo');
INSERT INTO user_country (name) VALUES('Costa Rica');
INSERT INTO user_country (name) VALUES('Croatia');
INSERT INTO user_country (name) VALUES('Cuba');
INSERT INTO user_country (name) VALUES('Cyprus');
INSERT INTO user_country (name) VALUES('Czech Republic');
INSERT INTO user_country (name) VALUES('Democratic Republic of the Congo');
INSERT INTO user_country (name) VALUES('Denmark');
INSERT INTO user_country (name) VALUES('Djibouti');
INSERT INTO user_country (name) VALUES('Dominican Republic');
INSERT INTO user_country (name) VALUES('Dominica');
INSERT INTO user_country (name) VALUES('Ecuador');
INSERT INTO user_country (name) VALUES('Egypt');
INSERT INTO user_country (name) VALUES('El Salvador');
INSERT INTO user_country (name) VALUES('Equatorial Guinea');
INSERT INTO user_country (name) VALUES('Eritrea');
INSERT INTO user_country (name) VALUES('Estonia');
INSERT INTO user_country (name) VALUES('Ethiopia');
INSERT INTO user_country (name) VALUES('Fiji');
INSERT INTO user_country (name) VALUES('Finland');
INSERT INTO user_country (name) VALUES('France');
INSERT INTO user_country (name) VALUES('French Guiana');
INSERT INTO user_country (name) VALUES('Gabon');
INSERT INTO user_country (name) VALUES('Gambia');
INSERT INTO user_country (name) VALUES('Georgia');
INSERT INTO user_country (name) VALUES('Germany');
INSERT INTO user_country (name) VALUES('Ghana');
INSERT INTO user_country (name) VALUES('Great Britain');
INSERT INTO user_country (name) VALUES('Greece');
INSERT INTO user_country (name) VALUES('Grenada');
INSERT INTO user_country (name) VALUES('Guadeloupe');
INSERT INTO user_country (name) VALUES('Guatemala');
INSERT INTO user_country (name) VALUES('Guinea');
INSERT INTO user_country (name) VALUES('Guinea-Bissau');
INSERT INTO user_country (name) VALUES('Guyana');
INSERT INTO user_country (name) VALUES('Haiti');
INSERT INTO user_country (name) VALUES('Honduras');
INSERT INTO user_country (name) VALUES('Hungary');
INSERT INTO user_country (name) VALUES('Iceland');
INSERT INTO user_country (name) VALUES('India');
INSERT INTO user_country (name) VALUES('Indonesia');
INSERT INTO user_country (name) VALUES('Iran');
INSERT INTO user_country (name) VALUES('Iraq');
INSERT INTO user_country (name) VALUES('Israel and the Occupied Territories');
INSERT INTO user_country (name) VALUES('Italy');
INSERT INTO user_country (name) VALUES('Ivory Coast (Cote d''Ivoire)');
INSERT INTO user_country (name) VALUES('Jamaica');
INSERT INTO user_country (name) VALUES('Japan');
INSERT INTO user_country (name) VALUES('Jordan');
INSERT INTO user_country (name) VALUES('Kazakhstan');
INSERT INTO user_country (name) VALUES('Kenya');
INSERT INTO user_country (name) VALUES('Kosovo');
INSERT INTO user_country (name) VALUES('Kuwait');
INSERT INTO user_country (name) VALUES('Kyrgyz Republic (Kyrgyzstan)');
INSERT INTO user_country (name) VALUES('Laos');
INSERT INTO user_country (name) VALUES('Latvia');
INSERT INTO user_country (name) VALUES('Lebanon');
INSERT INTO user_country (name) VALUES('Lesotho');
INSERT INTO user_country (name) VALUES('Liberia');
INSERT INTO user_country (name) VALUES('Libya');
INSERT INTO user_country (name) VALUES('Liechtenstein');
INSERT INTO user_country (name) VALUES('Lithuania');
INSERT INTO user_country (name) VALUES('Luxembourg');
INSERT INTO user_country (name) VALUES('Republic of Macedonia');
INSERT INTO user_country (name) VALUES('Madagascar');
INSERT INTO user_country (name) VALUES('Malawi');
INSERT INTO user_country (name) VALUES('Malaysia');
INSERT INTO user_country (name) VALUES('Maldives');
INSERT INTO user_country (name) VALUES('Mali');
INSERT INTO user_country (name) VALUES('Malta');
INSERT INTO user_country (name) VALUES('Martinique');
INSERT INTO user_country (name) VALUES('Mauritania');
INSERT INTO user_country (name) VALUES('Mauritius');
INSERT INTO user_country (name) VALUES('Mayotte');
INSERT INTO user_country (name) VALUES('Mexico');
INSERT INTO user_country (name) VALUES('Moldova, Republic of');
INSERT INTO user_country (name) VALUES('Monaco');
INSERT INTO user_country (name) VALUES('Mongolia');
INSERT INTO user_country (name) VALUES('Montenegro');
INSERT INTO user_country (name) VALUES('Montserrat');
INSERT INTO user_country (name) VALUES('Morocco');
INSERT INTO user_country (name) VALUES('Mozambique');
INSERT INTO user_country (name) VALUES('Namibia');
INSERT INTO user_country (name) VALUES('Nepal');
INSERT INTO user_country (name) VALUES('Netherlands');
INSERT INTO user_country (name) VALUES('New Zealand');
INSERT INTO user_country (name) VALUES('Nicaragua');
INSERT INTO user_country (name) VALUES('Niger');
INSERT INTO user_country (name) VALUES('Nigeria');
INSERT INTO user_country (name) VALUES('Korea, Democratic Republic of (North Korea)');
INSERT INTO user_country (name) VALUES('Norway');
INSERT INTO user_country (name) VALUES('Oman');
INSERT INTO user_country (name) VALUES('Pacific Islands');
INSERT INTO user_country (name) VALUES('Pakistan');
INSERT INTO user_country (name) VALUES('Panama');
INSERT INTO user_country (name) VALUES('Papua New Guinea');
INSERT INTO user_country (name) VALUES('Paraguay');
INSERT INTO user_country (name) VALUES('Peru');
INSERT INTO user_country (name) VALUES('Philippines');
INSERT INTO user_country (name) VALUES('Poland');
INSERT INTO user_country (name) VALUES('Portugal');
INSERT INTO user_country (name) VALUES('Puerto Rico');
INSERT INTO user_country (name) VALUES('Qatar');
INSERT INTO user_country (name) VALUES('Reunion');
INSERT INTO user_country (name) VALUES('Romania');
INSERT INTO user_country (name) VALUES('Russian Federation');
INSERT INTO user_country (name) VALUES('Rwanda');
INSERT INTO user_country (name) VALUES('Saint Kitts and Nevis');
INSERT INTO user_country (name) VALUES('Saint Lucia');
INSERT INTO user_country (name) VALUES('Saint Vincent''s & Grenadines');
INSERT INTO user_country (name) VALUES('Samoa');
INSERT INTO user_country (name) VALUES('Sao Tome and Principe');
INSERT INTO user_country (name) VALUES('Saudi Arabia');
INSERT INTO user_country (name) VALUES('Senegal');
INSERT INTO user_country (name) VALUES('Serbia');
INSERT INTO user_country (name) VALUES('Seychelles');
INSERT INTO user_country (name) VALUES('Sierra Leone');
INSERT INTO user_country (name) VALUES('Singapore');
INSERT INTO user_country (name) VALUES('Slovak Republic (Slovakia)');
INSERT INTO user_country (name) VALUES('Slovenia');
INSERT INTO user_country (name) VALUES('Solomon Islands');
INSERT INTO user_country (name) VALUES('Somalia');
INSERT INTO user_country (name) VALUES('South Africa');
INSERT INTO user_country (name) VALUES('Korea, Republic of (South Korea)');
INSERT INTO user_country (name) VALUES('South Sudan');
INSERT INTO user_country (name) VALUES('Spain');
INSERT INTO user_country (name) VALUES('Sri Lanka');
INSERT INTO user_country (name) VALUES('Sudan');
INSERT INTO user_country (name) VALUES('Suriname');
INSERT INTO user_country (name) VALUES('Swaziland');
INSERT INTO user_country (name) VALUES('Sweden');
INSERT INTO user_country (name) VALUES('Switzerland');
INSERT INTO user_country (name) VALUES('Syria');
INSERT INTO user_country (name) VALUES('Tajikistan');
INSERT INTO user_country (name) VALUES('Tanzania');
INSERT INTO user_country (name) VALUES('Thailand');
INSERT INTO user_country (name) VALUES('Timor Leste');
INSERT INTO user_country (name) VALUES('Togo');
INSERT INTO user_country (name) VALUES('Trinidad & Tobago');
INSERT INTO user_country (name) VALUES('Tunisia');
INSERT INTO user_country (name) VALUES('Turkey');
INSERT INTO user_country (name) VALUES('Turkmenistan');
INSERT INTO user_country (name) VALUES('Turks & Caicos Islands');
INSERT INTO user_country (name) VALUES('Uganda');
INSERT INTO user_country (name) VALUES('Ukraine');
INSERT INTO user_country (name) VALUES('United Arab Emirates');
INSERT INTO user_country (name) VALUES('United States of America (USA)');
INSERT INTO user_country (name) VALUES('Uruguay');
INSERT INTO user_country (name) VALUES('Uzbekistan');
INSERT INTO user_country (name) VALUES('Venezuela');
INSERT INTO user_country (name) VALUES('Vietnam');
INSERT INTO user_country (name) VALUES('Virgin Islands (UK)');
INSERT INTO user_country (name) VALUES('Virgin Islands (US)');
INSERT INTO user_country (name) VALUES('Yemen');
INSERT INTO user_country (name) VALUES('Zambia');
INSERT INTO user_country (name) VALUES('Zimbabwe');

/*Status table*/
INSERT INTO user_status (name) VALUES('Waiting');
INSERT INTO user_status (name) VALUES('Accepted');
INSERT INTO user_status (name) VALUES('Declined');

/*Payment table*/
INSERT INTO user_payment ("PaymentMethod", "PreferredPayment") VALUES('paypal',False);
INSERT INTO user_payment ("PaymentMethod", "PreferredPayment") VALUES('mastercard',False);

/*User table*/
INSERT INTO user_user ("Email","PasswordEncrypt","Username","StreetName","Zip","City","Picture","PreferredPaymentID_id","CountryID_id") VALUES('aaa@aaa','aaa','aaa','aaa 1','1','a','a.jpg','1','2');
INSERT INTO user_user ("Email","PasswordEncrypt","Username","StreetName","Zip","City","Picture","PreferredPaymentID_id","CountryID_id") VALUES('bbb@bbb','bbb','bbb','bbb 2','2','b','b.jpg','1','12');
>>>>>>> aslaugtestbranch

/*Bid table*/
INSERT INTO user_bid ("ProductID_id","BuyerID_id","PaymentID_id","StatusID_id") VALUES(1,1,1,1);
INSERT INTO user_bid ("ProductID_id","BuyerID_id","PaymentID_id","StatusID_id") VALUES(2,2,2,2);