# Generated by Django 4.0.4 on 2022-05-06 22:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='CreatedAt',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 6, 22, 51, 24, 640598, tzinfo=utc)),
        ),
    ]
