# Generated by Django 4.0.4 on 2022-05-03 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ConditionID',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='product.condition'),
            preserve_default=False,
        ),
    ]
