# Generated by Django 4.0.4 on 2022-05-10 09:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_createdat'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='picturedata',
            field=models.ImageField(blank=True, null=True, upload_to=product.models.uuid_imagepath),
        ),
        migrations.AlterField(
            model_name='product',
            name='CreatedAt',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 10, 9, 39, 28, 873316, tzinfo=utc)),
        ),
    ]
