# Generated by Django 4.0.4 on 2022-05-11 08:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_createdat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='CreatedAt',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 11, 8, 12, 47, 103463, tzinfo=utc)),
        ),
    ]
