# Generated by Django 4.0.4 on 2022-05-04 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_payment_preferredpayment'),
        ('product', '0004_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sellerID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.user'),
            preserve_default=False,
        ),
    ]
