# Generated by Django 4.0.4 on 2022-05-04 15:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_product_createdat_alter_product_soldornot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='CreatedAt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 4, 15, 43, 55, 358807, tzinfo=utc)),
        ),
    ]
