# Generated by Django 4.0.4 on 2022-05-11 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_picture_picture_alter_product_createdat'),
        ('product', '0007_alter_product_createdat'),
    ]

    operations = [
    ]
