# Generated by Django 4.0.4 on 2022-05-04 15:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_product_createdat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='CreatedAt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 4, 15, 44, 37, 167943, tzinfo=utc)),
        ),
    ]
