# Generated by Django 4.0.4 on 2022-05-04 16:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_product_createdat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='CreatedAt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 4, 16, 52, 58, 311521)),
        ),
    ]
