# Generated by Django 4.0.4 on 2022-05-04 17:03

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_product_createdat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='CreatedAt',
            field=models.DateTimeField(blank=True, default=django.utils.datetime_safe.new_datetime),
        ),
    ]
