# Generated by Django 4.0.4 on 2022-05-05 11:10

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_payment_preferredpayment'),
        ('product', '0010_alter_product_createdat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='CreatedAt',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 5, 11, 10, 3, 271633, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='SoldOrNot',
            field=models.IntegerField(default='0'),
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=9999)),
                ('stars', models.IntegerField()),
                ('buyerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
                ('productID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
    ]
