# Generated by Django 4.0.4 on 2022-05-05 11:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_product_createdat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ConditionID',
            field=models.ForeignKey(on_delete=models.SET(0), to='product.condition'),
        ),
        migrations.AlterField(
            model_name='product',
            name='CreatedAt',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 5, 11, 22, 35, 251887, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='SoldOrNot',
            field=models.IntegerField(default='0'),
        ),
    ]
