# Generated by Django 4.0.4 on 2022-05-05 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_product_conditionid_alter_product_createdat_and_more'),
        ('product', '0011_alter_product_createdat_alter_product_soldornot_and_more'),
    ]

    operations = [
    ]
