# Generated by Django 4.0.4 on 2022-05-05 13:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_merge_20220505_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='CreatedAt',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 5, 13, 22, 24, 852991, tzinfo=utc)),
        ),
    ]
