# Generated by Django 4.0.4 on 2022-05-03 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserID', models.FloatField()),
                ('Email', models.CharField(max_length=255)),
                ('PasswordEncrypt', models.CharField(max_length=255)),
                ('Username', models.CharField(max_length=255)),
                ('StreetName', models.CharField(max_length=255)),
                ('Zip', models.FloatField()),
                ('City', models.CharField(max_length=255)),
                ('Picture', models.CharField(max_length=255)),
                ('CountryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.country')),
            ],
        ),
    ]
