# Generated by Django 4.0.4 on 2022-05-03 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PaymentMethod', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='UserID',
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BuyerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
                ('PaymentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.payment')),
                ('ProductID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('StatusID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.status')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='PreferredPaymentID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.payment'),
        ),
    ]
