# Generated by Django 4.0.4 on 2022-05-04 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_payment_status_remove_user_userid_bid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='PreferredPayment',
            field=models.BooleanField(default=0),
        ),
    ]
