# Generated by Django 4.0.4 on 2022-05-07 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='User',
            new_name='user',
        ),
    ]
