# Generated by Django 4.0.4 on 2022-05-05 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_payment_preferredpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='BidAmount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='CountryID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.country'),
        ),
        migrations.AlterField(
            model_name='user',
            name='PreferredPaymentID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.payment'),
        ),
        migrations.AlterField(
            model_name='user',
            name='Zip',
            field=models.FloatField(default=0),
        ),
    ]
