# Generated by Django 4.0.4 on 2022-05-11 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_bid_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Bio',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
