# Generated by Django 4.0.4 on 2022-05-05 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_bid_bidamount_alter_user_countryid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='StatusID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.status'),
        ),
    ]
