# Generated by Django 4.0.4 on 2022-05-13 10:43

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_remove_order_countryid_remove_order_bid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Picture',
            field=models.ImageField(blank=True, null=True, upload_to=product.models.uuid_imagepath),
        ),
    ]
